apiVersion: v1
kind: PersistentVolume
metadata:
  name: treehub-pv-1
  labels:
    type: local
    volume: treehub
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
{{ if .gce }}
  gcePersistentDisk:
    pdName: treehub-pv-1
    fsType: ext4
{{ else }}
  hostPath:
    path: /data/treehub-pv-1
{{ end }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-1
  labels:
    type: local
    volume: mysql
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
{{ if .gce }}
  gcePersistentDisk:
    pdName: mysql-pv-1
    fsType: ext4
{{ else }}
  hostPath:
    path: /data/mysql-pv-1
{{ end }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv-1
  labels:
    type: local
    volume: zookeeper
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
{{ if .gce }}
  gcePersistentDisk:
    pdName: zookeeper-pv-1
    fsType: ext4
{{ else }}
  hostPath:
    path: /data/zookeeper-pv-1
{{ end }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-1
  labels:
    type: local
    volume: kafka
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
{{ if .gce }}
  gcePersistentDisk:
    pdName: kafka-pv-1
    fsType: ext4
{{ else }}
  hostPath:
    path: /data/kafka-pv-1
{{ end }}
